services:
  brew-haven:
    build: .

    image: brew-haven:1.0.1

    container_name: brew-haven

    restart: unless-stopped

    environment:
      NODE_ENV: production
      PORT: 3000

    ports:
      - "3000:3000"