pipeline {
    agent any

    environment {
        IMAGE_NAME = "shamyugtha/week03-node-app"
        IMAGE_TAG = "v1"
    }

    stages {

        stage('Environment Validation') {
            steps {
                sh 'git --version'
                sh 'docker --version'
            }
        }

        stage('Verify Project Files') {
            steps {
                dir('week-03-docker') {
                    sh 'pwd'
                    sh 'ls -la'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('week-03-docker') {
                    sh 'docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .'
                }
            }
        }

        stage('Verify Docker Image') {
            steps {
                sh 'docker images'
            }
        }
    }
}
