pipeline {
    agent any

    environment {
        IMAGE_NAME = "shamyugtha/week03-node-app"
        IMAGE_TAG = "v1"
    }

    stages {

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .'
            }
        }

        stage('Verify Image') {
            steps {
                sh 'docker images'
            }
        }
    }
}
