pipeline {
    agent any

    environment {
        IMAGE_NAME = "shamyugtha/week03-node-app"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Git Tool Verification') {
            steps {
                sh '''
                    echo "Checking Git location..."
                    which git

                    echo "Checking Git version..."
                    git --version

                    echo "Current PATH:"
                    echo $PATH
                '''
            }
        }

        stage('Environment Validation') {
            steps {
                sh 'git --version'
                sh 'docker --version'
            }
        }

        stage('Unit Tests') {
            steps {
                dir('week-03-docker') {
                    sh 'npm ci'
                    sh 'npm test'
                }
            }
        }

        stage('Verify Project Files') {
            steps {
                dir('week-03-docker') {
                    sh 'ls -la'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('week-03-docker') {
                    sh 'docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .'
                }
            }
        }

        stage('Verify Docker Image') {
            steps {
                sh 'docker images'
            }
        }

        stage('Docker Hub Login') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub-creds',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {
                    sh '''
                    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                    '''
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh 'docker push ${IMAGE_NAME}:${IMAGE_TAG}'
            }
        }
    }

    post {
        always {
            sh 'docker logout || true'
            echo 'Pipeline completed'
        }
    }
}