name: CI/CD Pipeline

on:
push:
branches:
- main

env:
IMAGE_NAME: shamyugtha/week03-node-app

jobs:
build-test-push:
runs-on: ubuntu-latest

```
steps:
  - name: Checkout Repository
    uses: actions/checkout@v4

  - name: Setup Node.js
    uses: actions/setup-node@v4
    with:
      node-version: 22

  - name: Environment Validation
    run: |
      git --version
      docker --version
      node --version
      npm --version

  - name: Install Dependencies
    working-directory: week-03-docker
    run: npm ci

  - name: Run Unit Tests
    working-directory: week-03-docker
    run: npm test

  - name: Verify Project Files
    working-directory: week-03-docker
    run: ls -la

  - name: Build Docker Image
    working-directory: week-03-docker
    run: |
      docker build -t $IMAGE_NAME:${{ github.run_number }} .

  - name: Verify Docker Image
    run: docker images

  - name: Login to Docker Hub
    uses: docker/login-action@v3
    with:
      username: ${{ secrets.DOCKER_USER }}
      password: ${{ secrets.DOCKER_PASS }}

  - name: Push Docker Image
    run: |
      docker push $IMAGE_NAME:${{ github.run_number }}
```
